Elearning\CoursesBundle\Entity\Course:
    properties:
        name:
            - NotBlank: ~
        category:
            - NotNull: ~
        description:
            - NotBlank: ~
        listenperiod:
            - NotBlank: ~