elearning_companies:
    resource: "@ElearningCompaniesBundle/Resources/config/routing.yml"
    prefix: /

elearning_courses:
    resource: "@ElearningCoursesBundle/Resources/config/routing.yml"
    prefix: /

# Custom Reflection Routes
student_reflection_list:
    path: /reflections
    defaults: { _controller: ElearningCoursesBundle:StudentReflection:list }

student_reflection_create:
    path: /reflections/create
    defaults: { _controller: ElearningCoursesBundle:StudentReflection:create }

student_reflection_view:
    path: /reflections/{id}
    defaults: { _controller: ElearningCoursesBundle:StudentReflection:view }

teacher_reflection_list:
    path: /teacher/reflections
    defaults: { _controller: ElearningCoursesBundle:TeacherReflection:list }

teacher_reflection_view:
    path: /teacher/reflections/{id}
    defaults: { _controller: ElearningCoursesBundle:TeacherReflection:view }

teacher_reflection_respond:
    path: /teacher/reflections/{id}/respond
    defaults: { _controller: ElearningCoursesBundle:TeacherReflection:respond }

elearning_main:
    resource: "@ElearningMainBundle/Resources/config/routing.yml"
    prefix: /

elearning_user:
    resource: "@ElearningUserBundle/Resources/config/routing.yml"
    prefix: /

app:
    resource: "@AppBundle/Controller/"
    type: annotation

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

sonata_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

sonata_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

sonata_user:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"
    prefix: /admin

sonata_user_admin_resetting_request:
    path: /admin/resetting/request
    defaults:
        {
            _controller: FrameworkBundle:Redirect:redirect,
            route: fos_user_resetting_request,
            permanent: false,
        }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
