security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    firewalls:
        # Disabling the security for the web debug toolbar, the profiler and Assetic.
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # -> custom firewall for the admin area of the URL
        admin:
            pattern: /admin(.*)
            context: user
            form_login:
                provider: fos_userbundle
                login_path: /admin/login
                use_forward: false
                check_path: /admin/login_check
                failure_path: null
            logout:
                path: sonata_user_admin_security_logout
            anonymous: true

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                # csrf_provider: form.csrf_provider # Removed in Symfony 3.0
                csrf_token_generator: security.csrf.token_manager
                username_parameter: _username
                login_path: /
            logout:
                path: fos_user_security_logout
            anonymous: true

    access_control:
        # The WDT has to be allowed to anonymous users to avoid requiring the login with the AJAX request
        - { path: ^/wdt/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profiler/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Allow access to API methods for guest
        - { path: ^/api/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # AsseticBundle paths used when using the controller for assets
        - { path: ^/js/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/css/, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # URL of FOSUserBundle which need to be available to anonymous users
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Admin login page needs to be access without credential
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        # Secured part of the site
        # This config requires being logged for the whole site and having the admin role for the admin part.
        # Change these rules to adapt them to your needs
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_MANAGER: [ROLE_USER, ROLE_COURSES_MANAGER]
        ROLE_LECTURER: [ROLE_USER, ROLE_COURSES_LECTURER]
        ROLE_STUDENT: [ROLE_USER, ROLE_COURSES_STUDENT]
        ROLE_SUPERVISOR: [ROLE_USER, ROLE_COURSES_SUPERVISOR]
        ROLE_FORCECREDENTIALCHANGE: [ROLE_USER]
        ROLE_ADMIN:
            [
                ROLE_USER,
                ROLE_SONATA_ADMIN,
                ROLE_MANAGER,
                ROLE_LECTURER,
                ROLE_STUDENT,
                ROLE_SUPERVISOR,
                ROLE_FORCECREDENTIALCHANGE,
            ]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    acl:
        connection: default

    # set access_strategy to unanimous, else you may have unexpected behaviors
    access_decision_manager:
        strategy: unanimous
