Elearning\UserBundle\Entity\Group:
    type:  entity
    table: fos_group
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToMany:
        users:
            targetEntity: Elearning\UserBundle\Entity\User
            mappedBy: groups
