Elearning\CoursesBundle\Entity\Feedback:
    type: entity
    table: crs_feedbacks
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        chapter_id:
            type: integer
            nullable: false
        data:
            type: text
            nullable: false
        version:
            type: string
            nullable: false
            options:
                default: "edit"
    oneToMany:
        answers:
            targetEntity: Elearning\CoursesBundle\Entity\FeedbackData
            mappedBy: feedback
    manyToOne:
        chapter:
            targetEntity: Elearning\CoursesBundle\Entity\Chapter
            joinColumn:
                name: chapter_id
                referencedColumnName: id


